### ISSUE TITLE
no expand tab in question

### ISSUE THREAD

**Issue by oleastre** [grafana/vim-alloy#3]
Hello,

I just switched to alloy  from promtail, and started using this plugin. 
Could you explain me the need to disable tab expansion in `ftplugin/alloy.vim` ? 
Form me this is a style question that should be left to the plugin user, not a need of the file format. Or did I miss something ?

**Comment by rfratto** [comment]
Hi, disabling tab expansion aligns with how the Alloy syntax formatter works (`alloy fmt` / `alloy format`), where it takes the opinionated stance that files should be tab indented, avoiding arguments around how many spaces to indent. Enforcing tabs for indentation also allows users to pick their own tab width in their editor.

**Comment by oleastre** [comment]
Ok, makes sense if that's the formatter's default. 
A bit surprising, while most of the tools/languages I use use spaces,  but I can live with that.
